/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#000000",
        "error": "#ba1a1a",
        "inverse-primary": "#bac7e1",
        "on-tertiary-container": "#b87500",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffddb8",
        "outline": "#75777d",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container": "#e7eeff",
        "on-primary-fixed-variant": "#3a475c",
        "secondary-fixed-dim": "#4edea3",
        "outline-variant": "#c5c6cd",
        "surface-container-low": "#f0f3ff",
        "surface-tint": "#525f75",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-container": "#77849c",
        "secondary-fixed": "#6ffbbe",
        "surface-dim": "#cfdaf2",
        "on-tertiary-fixed": "#2a1700",
        "inverse-surface": "#263143",
        "inverse-on-surface": "#ecf1ff",
        "secondary": "#006c49",
        "on-background": "#111c2d",
        "tertiary-container": "#2a1700",
        "primary": "#000000",
        "on-secondary-fixed-variant": "#005236",
        "on-surface": "#111c2d",
        "surface-variant": "#d8e3fb",
        "on-surface-variant": "#44474c",
        "primary-fixed": "#d6e3fe",
        "on-secondary-container": "#00714d",
        "on-error-container": "#93000a",
        "secondary-container": "#6cf8bb",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-lowest": "#ffffff",
        "background": "#f9f9ff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#0e1c2f",
        "primary-fixed-dim": "#bac7e1",
        "primary-container": "#0e1c2f",
        "surface-container-highest": "#d8e3fb",
        "surface-container-high": "#dee8ff",
        "surface": "#f9f9ff",
        "on-secondary-fixed": "#002113"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "1.5rem",
        "space-lg": "1rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "margin-mobile": "0.75rem",
        "gutter-mobile": "0.75rem",
        "space-xs": "0.25rem",
        "margin": "1rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "currency-display": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "tabular-data": ["Inter", "monospace"],
        "currency-display-mobile": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-md": ["13px", { "lineHeight": "18px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "currency-display": ["28px", { "lineHeight": "34px", "fontWeight": "800" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "tabular-data": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "currency-display-mobile": ["22px", { "lineHeight": "28px", "fontWeight": "800" }]
      }
    }
  }
};
